variables:
  VERSION_ID: '1.0.$CI_PIPELINE_ID'

stages:
- build

build:
  image: slauta93/electron-builder-win
  stage: build
  artifacts:
    paths:
    - dist/*-mac.zip
    - dist/*-amd64.deb

  script:
  - apt-get update
  - apt-get install libsecret-1-0
  - npm install
  - npm run dist
